//Teste requisições REST - Livros

@baseUrl =http://localhost:4000

@id =60bf8de0dfa60710b3c8ca0e

###
GET {{baseUrl}}/items
Content-Type: application/json

###
DELETE {{baseUrl}}/{{id}}
Content-Type: application/json